import { StyleSheet } from "react-native";

export const COLORS = {
  bg: "#080a0d",
  panel: "#12161c",
  border: "#232a33",
  text: "#f7f8f5",
  muted: "#7e8691",
  dim: "#5b636e",
  acid: "#a3e635",
  violet: "#8b7bff",
  amber: "#f59e0b",
  red: "#e5484d",
};

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: COLORS.bg },
  scroll: { padding: 20, paddingTop: 64, paddingBottom: 48, gap: 14 },
  eyebrow: { color: COLORS.acid, fontSize: 10, fontWeight: "700", letterSpacing: 2 },
  h1: { color: COLORS.text, fontSize: 30, fontWeight: "700", marginTop: 6, letterSpacing: -0.5 },
  lede: { color: COLORS.muted, fontSize: 14, lineHeight: 21, marginBottom: 8 },
  card: {
    backgroundColor: COLORS.panel,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: 20,
    padding: 16,
    gap: 8,
  },
  videoCard: {
    backgroundColor: COLORS.panel,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: 20,
    padding: 10,
    gap: 8,
  },
  videoWrap: { position: "relative", borderRadius: 12, overflow: "hidden" },
  video: { width: "100%", aspectRatio: 9 / 16, backgroundColor: "#000" },
  marker: { position: "absolute", top: 0, bottom: 0, width: 2, backgroundColor: COLORS.text },
  cardHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
  cardTitle: { color: COLORS.text, fontSize: 15, fontWeight: "700", flexShrink: 1 },
  question: { color: COLORS.text, fontSize: 13, lineHeight: 19 },
  why: { color: COLORS.muted, fontSize: 12, lineHeight: 18 },
  detail: { color: COLORS.dim, fontSize: 11, lineHeight: 17, fontStyle: "italic" },
  result: {
    color: COLORS.acid,
    fontSize: 11,
    lineHeight: 17,
    fontFamily: "monospace",
  },
  error: { color: COLORS.red, fontSize: 11, lineHeight: 17 },
  chip: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3 },
  chipText: { fontSize: 9, fontWeight: "700", letterSpacing: 1 },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 3 },
  rowK: { color: COLORS.muted, fontSize: 13 },
  rowV: { color: COLORS.text, fontSize: 13, fontWeight: "600" },
  button: {
    marginTop: 4,
    backgroundColor: COLORS.violet,
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: "center",
  },
  buttonDisabled: { opacity: 0.45 },
  buttonText: { color: COLORS.text, fontSize: 13, fontWeight: "700" },
  footer: { color: COLORS.dim, fontSize: 11, lineHeight: 17, marginTop: 6 },
});
