/**
 * Single source for both generating and verifying `src/generated/`.
 *
 * Both entry points call `compileOne()` here with identical options and compare raw output. An
 * earlier version stripped leading comments before comparing, which was asymmetric: it removed
 * the banner from the committed file and the first JSDoc block from the freshly-compiled one,
 * so the check failed on a file nobody had touched. A drift check that cries wolf is worse than
 * none, because people learn to skip it.
 *
 * `additionalProperties: false` here is a CODEGEN option, not a validation one, and the split is
 * deliberate. The schemas leave `additionalProperties` unset, so Ajv accepts unknown fields — a
 * client built for schema 9 must tolerate an artifact written at 11. Telling the compiler to
 * assume `false` keeps `[k: string]: unknown` index signatures out of every generated interface,
 * which would otherwise defeat the point of generating types at all. Permissive validation,
 * precise types.
 */
import { readdirSync } from "node:fs";
import { basename, join } from "node:path";
import { compileFromFile } from "json-schema-to-typescript";

export const SCHEMA_DIR = "schemas";
export const OUT_DIR = "src/generated";

/** `analysis.schema.json` -> `analysis`; the generated file and its import specifier match. */
export const stemOf = (file) => basename(file).replace(/\.schema\.json$/, "");

/** Every contract in `schemas/`, discovered rather than listed — a new schema is generated by
 *  existing, so there is no second place to forget to register it. */
export function schemaFiles() {
  return readdirSync(SCHEMA_DIR)
    .filter((f) => f.endsWith(".schema.json"))
    .sort();
}

export const outPathFor = (file) => join(OUT_DIR, `${stemOf(file)}.ts`);

export const bannerFor = (file) =>
  `/* GENERATED from ${SCHEMA_DIR}/${file} - do not edit.\n` +
  ` * Run: pnpm --filter @swingsage/schema generate */`;

export const compileOne = (file) =>
  compileFromFile(join(SCHEMA_DIR, file), {
    bannerComment: bannerFor(file),
    additionalProperties: false,
    declareExternallyReferenced: true,
    unreachableDefinitions: true,
  });
