"""Extract a hermetic test input from a stored analysis.json.

The golden snapshot tests must run on a fresh clone with no video, no GPU and no `out/`
directory — `out/` is gitignored and regenerating it costs minutes per clip. So the pose and
club *outputs* are frozen into a small committed file and the tests replay only the
deterministic stages over them: events -> checkpoints -> metrics.

That split is deliberate. Pose is the slow, hardware-dependent stage; everything after it is
arithmetic. Freezing pose as an input means a change to inference (a TensorRT/FP16 port, a new
model) shows up as a golden diff on every downstream number instead of hiding inside one, and a
change to the *math* can be tested in milliseconds without touching a GPU.

    python scripts/make_test_data.py swing1 swing2
    python scripts/make_test_data.py --all
"""
from __future__ import annotations

import argparse
import gzip
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "out"
DEST = ROOT / "tests" / "data"


def extract(stem: str) -> Path:
    src = OUT / stem / "analysis.json"
    if not src.exists():
        raise SystemExit(f"no analysis.json for {stem} — run burnin.py first ({src})")
    a = json.loads(src.read_text(encoding="utf-8"))

    v = a["video"]
    club = a.get("club") or {}
    # Only what checkpoints.build() and metrics.compute() actually read off a club frame. The
    # full club block carries shaft/butt/trace per frame and would dominate the file.
    club_frames = [{"f": c["f"], "head": c.get("head"), "conf": c.get("conf")}
                   for c in (club.get("frames") or [])]

    payload = {
        "stem": stem,
        "note": "Frozen analyzer input for golden tests. Generated by "
                "scripts/make_test_data.py — do not hand-edit.",
        "source_schema": a.get("schema_version"),
        "video": {k: v[k] for k in ("fps", "width", "height", "frame_count", "view",
                                    "handedness") if k in v},
        "pose": {"model": a["pose"]["model"],
                 "keypoint_names": a["pose"]["keypoint_names"],
                 "frames": a["pose"]["frames"]},
        "club_frames": club_frames or None,
        "club_len": club.get("club_len"),
    }

    DEST.mkdir(parents=True, exist_ok=True)
    dst = DEST / f"{stem}.input.json.gz"
    with gzip.open(dst, "wt", encoding="utf-8") as fh:
        json.dump(payload, fh, separators=(",", ":"))
    kb = dst.stat().st_size / 1024
    print(f"{stem:10s} -> {dst.relative_to(ROOT)}  ({kb:.0f} KB gz, "
          f"{len(payload['pose']['frames'])} frames, "
          f"{len(club_frames)} club frames, schema {payload['source_schema']})")
    return dst


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("stems", nargs="*")
    ap.add_argument("--all", action="store_true", help="every out/<stem> with an analysis.json")
    args = ap.parse_args()

    stems = args.stems
    if args.all or not stems:
        stems = sorted(p.parent.name for p in OUT.glob("*/analysis.json"))
    if not stems:
        raise SystemExit("nothing to extract")
    for s in stems:
        extract(s)


if __name__ == "__main__":
    main()
